---
- name: Install MicroK8s
  hosts: localhost
  become: true
  tasks:
    - name: Install MicroK8s
      command: sudo snap install microk8s --classic

- name: Enable MicroK8s Addons
  hosts: localhost
  become: true
  tasks:
    - name: Enable DNS and Dashboard addons
      command: sudo microk8s enable dns dashboard

- name: Wait for MicroK8s to be ready
  hosts: localhost
  become: true
  tasks:
    - name: Check MicroK8s status
      command: sudo microk8s status --wait-ready

- name: Deploy Nginx
  hosts: localhost
  become: true
  tasks:
    - name: Apply Nginx Deployment
      command: sudo microk8s kubectl apply -f nginx-deployment.yaml

- name: Expose Nginx Service
  hosts: localhost
  become: true
  tasks:
    - name: Apply Nginx Service
      command: sudo microk8s kubectl apply -f nginx-service.yaml

- name: Serve Nginx Locally
  hosts: localhost
  become: true
  tasks:
    - name: Port forward Nginx service locally
      command: sudo microk8s kubectl port-forward service/nginx-service 8070:80
