apiVersion: v1
kind: Service
metadata:
  name: emqx-service
spec:
  selector:
    app: emqx
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: websocket
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: dashboard
      protocol: TCP
      port: 18083
      targetPort: 18083
  type: NodePort
